import "./globals.css";

export const metadata = {
	title: "Wades Inc.",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className="text-[#757575] font-sans">{children}</body>
		</html>
	);
}
